---
fail_fast: true
default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-added-large-files
        exclude: cclib_custom/tests/data
  - repo: https://github.com/PyCQA/isort
    rev: "5.12.0"
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: "23.1.0"
    hooks:
      - id: black
  # - repo: https://github.com/PyCQA/flake8
  #   rev: "4.0.1"
  #   hooks:
  #     - id: flake8
  # - repo: https://github.com/PyCQA/pylint
  #   rev: "v2.14.4"
  #   hooks:
  #     - id: pylint
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.1.1"
    hooks:
      - id: mypy
        additional_dependencies:
          - cclib
          - numpy
          - pytest
          - types-pyyaml
          - types-setuptools
        args: []
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: "0.22.0"
    hooks:
      - id: check-github-workflows
